---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - Github:
        - icon: github.svg
          abbr: GH
          href: https://github.com/dave6892
    - Gitlab:
        - icon: gitlab.svg
          abbr: GL
          href: https://gitlab.com/dave6892

- Social:
    - Bluesky:
        - icon: bluesky.svg
          abbr: BL
          href: https://bsky.app/
    - Reddit:
        - icon: reddit.svg
          abbr: RE
          href: https://reddit.com/

- Entertainment:
    - YouTube:
        - icon: youtube.svg
          abbr: YT
          href: https://youtube.com/
