services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    # env_file:
    #   - stack.env
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: "America/Toronto"
      HOMEPAGE_ALLOWED_HOSTS: "*"
      HOMEPAGE_VAR_PORTAINER_URL: $HOMEPAGE_VAR_PORTAINER_URL
      HOMEPAGE_VAR_PORTAINER_API_KEY: $HOMEPAGE_VAR_PORTAINER_API_KEY
      HOMEPAGE_VAR_PLEX_URL: $HOMEPAGE_VAR_PLEX_URL
      HOMEPAGE_VAR_TAUTULLI_URL: $HOMEPAGE_VAR_TAUTULLI_URL
      HOMEPAGE_VAR_TAUTULLI_KEY: $HOMEPAGE_VAR_TAUTULLI_KEY
      HOMEPAGE_VAR_UPTIMEKUMA_URL: $HOMEPAGE_VAR_UPTIMEKUMA_URL
      HOMEPAGE_VAR_UPTIMEKUMA_SLUG: $HOMEPAGE_VAR_UPTIMEKUMA_SLUG
      HOMEPAGE_VAR_PROXMOX_URL: $HOMEPAGE_VAR_PROXMOX_URL
      HOMEPAGE_VAR_PROXMOX_USER: $HOMEPAGE_VAR_PROXMOX_USER
      HOMEPAGE_VAR_PROXMOX_PASSWORD: $HOMEPAGE_VAR_PROXMOX_PASSWORD
      HOMEPAGE_VAR_PROXMOX_API_KEY: $HOMEPAGE_VAR_PROXMOX_API_KEY
      HOMEPAGE_VAR_UNRAID_URL: $HOMEPAGE_VAR_UNRAID_URL
      HOMEPAGE_VAR_UNRAID_API_KEY: $HOMEPAGE_VAR_UNRAID_API_KEY
      HOMEPAGE_VAR_PIHOLE_URL: $HOMEPAGE_VAR_PIHOLE_URL
      HOMEPAGE_VAR_PIHOLE_API_KEY: $HOMEPAGE_VAR_PIHOLE_API_KEY
      HOMEPAGE_VAR_TRUENAS_URL: $HOMEPAGE_VAR_TRUENAS_URL
      HOMEPAGE_VAR_TRUENAS_API_KEY: $HOMEPAGE_VAR_TRUENAS_API_KEY
      HOMEPAGE_VAR_UNIFI_NETWORK_URL: $HOMEPAGE_VAR_UNIFI_NETWORK_URL
      HOMEPAGE_VAR_INFISICAL_URL: $HOMEPAGE_VAR_INFISICAL_URL
    volumes:
      - ./config/homepage:/config
    ports:
      - 3000:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`homepage.home`)"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.tls=true"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
    networks:
      - homelab
    restart: unless-stopped

networks:
  homelab:
    external: true
